# Generated by Django 3.2 on 2021-07-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_upload_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedDatabases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=10)),
                ('regulation', models.CharField(max_length=5)),
                ('semister', models.CharField(max_length=10)),
                ('examtype', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
