# Generated by Django 3.2 on 2021-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_createddatabases'),
    ]

    operations = [
        migrations.AddField(
            model_name='createddatabases',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
