# Generated by Django 3.2 on 2021-07-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_rename_no_of_branches_result_user_added_createddatabases_no_of_branches_result_user_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adding_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_branch_file', models.FileField(upload_to='csv_files/')),
                ('added_branch_name', models.CharField(max_length=30)),
                ('CDid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.createddatabases')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
