# Generated by Django 3.2 on 2021-07-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20210716_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adding_branch',
            name='CDid',
            field=models.IntegerField(),
        ),
    ]
