# Generated by Django 3.2 on 2021-07-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_adding_branch_cdid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Published_Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrData_id', models.IntegerField()),
                ('is_published', models.CharField(default='NO', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='createddatabases',
            name='is_published',
            field=models.IntegerField(default=0),
        ),
    ]
