# Generated by Django 3.2 on 2021-07-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20210717_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='adding_branch',
            name='table_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
